services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - DOCKER_TUTORIAL

  web:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"  
    volumes:
      - .:/app
    networks:
      - DOCKER_TUTORIAL

networks:
  DOCKER_TUTORIAL:
    name: DOCKER_TUTORIAL
    driver: bridge

volumes:
  postgres-data:
